name: On Windows

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [windows-latest]
        build_type: [Release]
        c_compiler: [cl, gcc]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: windows-latest
            c_compiler: gcc
            cpp_compiler: g++

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Install GTest
        run: choco install gtest -y

      - name: Configure CMake
        run: >
          cmake -B ${{ steps.strings.outputs.build-output-dir }}
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -S ${{ github.workspace }}

      - name: Build
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

#      - name: Upload artifacts
#        uses: actions/upload-artifact@v4
#        with:
#          name: build-output-${{ matrix.os }}-${{ matrix.c_compiler }}
#          path: ${{ steps.strings.outputs.build-output-dir }}
#          retention-days: 1

      - name: Test
        working-directory: build
        env:
          LD_LIBRARY_PATH: ${{ github.workspace }}/build
        #        run: ctest --build-config Release
        run: ctest --build-config Release --verbose --output-on-failure



#  test:
#    needs: build
#    runs-on: ${{ matrix.os }}
#
#    strategy:
#      fail-fast: false
#
#      matrix:
#        os: [windows-latest]
#        build_type: [Release]
#        c_compiler: [cl, mingw]
#
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Download artifacts
#        uses: actions/download-artifact@v4
#        with:
#          name: build-output-${{ matrix.os }}-${{ matrix.c_compiler }}
#          path: build
#
#      - name: Test
#        working-directory: build
#        run: ctest --build-config Release